services:
  database:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - db_storage:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=weight_tracking
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d weight_tracking"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  api:
    build: ./weight_tracking_api
    environment:
      DATABASE_URL: "postgresql://admin:admin@database/weight_tracking"
      HOST_URL: "0.0.0.0:7100"
      DOCUMENTATION_TARGET_URL: "http://localhost:7100"
    ports:
      - 7100:7100
    depends_on:
      database:
        condition: service_healthy

volumes:
  db_storage: {}

networks:
  default: